sudo: required

language: elixir

elixir: 1.8.0

otp_release: 21.2

addons:
  postgresql: 9.4

services:
  - redis-server

script:
  - MIX_ENV=test mix do ecto.create, ecto.load, test --exclude external:true

dist: precise
